/*
 * New Payment Gateway APIs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2022-01-01
 * Contact: nextgenapi@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.cashfree.pg.model;


import com.cashfree.pg.JSON;
import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Map.Entry;
import java.util.Objects;
import java.util.Set;

/**
 * The authorization details are present for payments which go through the preauthorization
 * workflow. Or else this parameter will be null.
 */
@javax.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        date = "2023-03-16T14:01:52.135917+05:30[Asia/Kolkata]")
public class CFAuthorizationInPaymentsEntity {
    /** One of CAPTURE or VOID */
    @JsonAdapter(ActionEnum.Adapter.class)
    public enum ActionEnum {
        CAPTURE("CAPTURE"),

        VOID("VOID");

        private String value;

        ActionEnum(String value) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        public static ActionEnum fromValue(String value) {
            for (ActionEnum b : ActionEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }

        public static class Adapter extends TypeAdapter<ActionEnum> {
            @Override
            public void write(final JsonWriter jsonWriter, final ActionEnum enumeration)
                    throws IOException {
                jsonWriter.value(enumeration.getValue());
            }

            @Override
            public ActionEnum read(final JsonReader jsonReader) throws IOException {
                String value = jsonReader.nextString();
                return ActionEnum.fromValue(value);
            }
        }
    }

    public static final String SERIALIZED_NAME_ACTION = "action";

    @SerializedName(SERIALIZED_NAME_ACTION)
    private ActionEnum action;

    /** One of SUCCESS or PENDING */
    @JsonAdapter(StatusEnum.Adapter.class)
    public enum StatusEnum {
        SUCCESS("SUCCESS"),

        PENDING("PENDING");

        private String value;

        StatusEnum(String value) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        public static StatusEnum fromValue(String value) {
            for (StatusEnum b : StatusEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }

        public static class Adapter extends TypeAdapter<StatusEnum> {
            @Override
            public void write(final JsonWriter jsonWriter, final StatusEnum enumeration)
                    throws IOException {
                jsonWriter.value(enumeration.getValue());
            }

            @Override
            public StatusEnum read(final JsonReader jsonReader) throws IOException {
                String value = jsonReader.nextString();
                return StatusEnum.fromValue(value);
            }
        }
    }

    public static final String SERIALIZED_NAME_STATUS = "status";

    @SerializedName(SERIALIZED_NAME_STATUS)
    private StatusEnum status;

    public static final String SERIALIZED_NAME_CAPTURED_AMOUNT = "captured_amount";

    @SerializedName(SERIALIZED_NAME_CAPTURED_AMOUNT)
    private BigDecimal capturedAmount;

    public static final String SERIALIZED_NAME_START_TIME = "start_time";

    @SerializedName(SERIALIZED_NAME_START_TIME)
    private String startTime;

    public static final String SERIALIZED_NAME_END_TIME = "end_time";

    @SerializedName(SERIALIZED_NAME_END_TIME)
    private String endTime;

    public static final String SERIALIZED_NAME_APPROVE_BY = "approve_by";

    @SerializedName(SERIALIZED_NAME_APPROVE_BY)
    private String approveBy;

    public CFAuthorizationInPaymentsEntity() {}

    public CFAuthorizationInPaymentsEntity action(ActionEnum action) {

        this.action = action;
        return this;
    }

    /**
     * One of CAPTURE or VOID
     *
     * @return action
     */
    @javax.annotation.Nullable
    public ActionEnum getAction() {
        return action;
    }

    public void setAction(ActionEnum action) {
        this.action = action;
    }

    public CFAuthorizationInPaymentsEntity status(StatusEnum status) {

        this.status = status;
        return this;
    }

    /**
     * One of SUCCESS or PENDING
     *
     * @return status
     */
    @javax.annotation.Nullable
    public StatusEnum getStatus() {
        return status;
    }

    public void setStatus(StatusEnum status) {
        this.status = status;
    }

    public CFAuthorizationInPaymentsEntity capturedAmount(BigDecimal capturedAmount) {

        this.capturedAmount = capturedAmount;
        return this;
    }

    /**
     * The captured amount for this authorization request
     *
     * @return capturedAmount
     */
    @javax.annotation.Nullable
    public BigDecimal getCapturedAmount() {
        return capturedAmount;
    }

    public void setCapturedAmount(BigDecimal capturedAmount) {
        this.capturedAmount = capturedAmount;
    }

    public CFAuthorizationInPaymentsEntity startTime(String startTime) {

        this.startTime = startTime;
        return this;
    }

    /**
     * Start time of this authorization hold (only for UPI)
     *
     * @return startTime
     */
    @javax.annotation.Nullable
    public String getStartTime() {
        return startTime;
    }

    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    public CFAuthorizationInPaymentsEntity endTime(String endTime) {

        this.endTime = endTime;
        return this;
    }

    /**
     * End time of this authorization hold (only for UPI)
     *
     * @return endTime
     */
    @javax.annotation.Nullable
    public String getEndTime() {
        return endTime;
    }

    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }

    public CFAuthorizationInPaymentsEntity approveBy(String approveBy) {

        this.approveBy = approveBy;
        return this;
    }

    /**
     * Approve by time as passed in the authorization request (only for UPI)
     *
     * @return approveBy
     */
    @javax.annotation.Nullable
    public String getApproveBy() {
        return approveBy;
    }

    public void setApproveBy(String approveBy) {
        this.approveBy = approveBy;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CFAuthorizationInPaymentsEntity cfAuthorizationInPaymentsEntity =
                (CFAuthorizationInPaymentsEntity) o;
        return Objects.equals(this.action, cfAuthorizationInPaymentsEntity.action)
                && Objects.equals(this.status, cfAuthorizationInPaymentsEntity.status)
                && Objects.equals(
                        this.capturedAmount, cfAuthorizationInPaymentsEntity.capturedAmount)
                && Objects.equals(this.startTime, cfAuthorizationInPaymentsEntity.startTime)
                && Objects.equals(this.endTime, cfAuthorizationInPaymentsEntity.endTime)
                && Objects.equals(this.approveBy, cfAuthorizationInPaymentsEntity.approveBy);
    }

    @Override
    public int hashCode() {
        return Objects.hash(action, status, capturedAmount, startTime, endTime, approveBy);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class CFAuthorizationInPaymentsEntity {\n");
        sb.append("    action: ").append(toIndentedString(action)).append("\n");
        sb.append("    status: ").append(toIndentedString(status)).append("\n");
        sb.append("    capturedAmount: ").append(toIndentedString(capturedAmount)).append("\n");
        sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
        sb.append("    endTime: ").append(toIndentedString(endTime)).append("\n");
        sb.append("    approveBy: ").append(toIndentedString(approveBy)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>();
        openapiFields.add("action");
        openapiFields.add("status");
        openapiFields.add("captured_amount");
        openapiFields.add("start_time");
        openapiFields.add("end_time");
        openapiFields.add("approve_by");

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>();
    }

    /**
     * Validates the JSON Object and throws an exception if issues found
     *
     * @param jsonObj JSON Object
     * @throws IOException if the JSON Object is invalid with respect to
     *     CFAuthorizationInPaymentsEntity
     */
    public static void validateJsonObject(JsonObject jsonObj) throws IOException {
        if (jsonObj == null) {
            if (!CFAuthorizationInPaymentsEntity.openapiRequiredFields
                    .isEmpty()) { // has required fields but JSON object is null
                throw new IllegalArgumentException(
                        String.format(
                                "The required field(s) %s in CFAuthorizationInPaymentsEntity is"
                                        + " not found in the empty JSON string",
                                CFAuthorizationInPaymentsEntity.openapiRequiredFields.toString()));
            }
        }

        Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
        // check to see if the JSON string contains additional fields
        for (Entry<String, JsonElement> entry : entries) {
            if (!CFAuthorizationInPaymentsEntity.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(
                        String.format(
                                "The field `%s` in the JSON string is not defined in the"
                                        + " `CFAuthorizationInPaymentsEntity` properties. JSON: %s",
                                entry.getKey(), jsonObj.toString()));
            }
        }
        if ((jsonObj.get("action") != null && !jsonObj.get("action").isJsonNull())
                && !jsonObj.get("action").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `action` to be a primitive type in the JSON string"
                                    + " but got `%s`",
                            jsonObj.get("action").toString()));
        }
        if ((jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull())
                && !jsonObj.get("status").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `status` to be a primitive type in the JSON string"
                                    + " but got `%s`",
                            jsonObj.get("status").toString()));
        }
        if ((jsonObj.get("start_time") != null && !jsonObj.get("start_time").isJsonNull())
                && !jsonObj.get("start_time").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `start_time` to be a primitive type in the JSON"
                                    + " string but got `%s`",
                            jsonObj.get("start_time").toString()));
        }
        if ((jsonObj.get("end_time") != null && !jsonObj.get("end_time").isJsonNull())
                && !jsonObj.get("end_time").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `end_time` to be a primitive type in the JSON"
                                    + " string but got `%s`",
                            jsonObj.get("end_time").toString()));
        }
        if ((jsonObj.get("approve_by") != null && !jsonObj.get("approve_by").isJsonNull())
                && !jsonObj.get("approve_by").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `approve_by` to be a primitive type in the JSON"
                                    + " string but got `%s`",
                            jsonObj.get("approve_by").toString()));
        }
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!CFAuthorizationInPaymentsEntity.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'CFAuthorizationInPaymentsEntity' and its
                // subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<CFAuthorizationInPaymentsEntity> thisAdapter =
                    gson.getDelegateAdapter(
                            this, TypeToken.get(CFAuthorizationInPaymentsEntity.class));

            return (TypeAdapter<T>)
                    new TypeAdapter<CFAuthorizationInPaymentsEntity>() {
                        @Override
                        public void write(JsonWriter out, CFAuthorizationInPaymentsEntity value)
                                throws IOException {
                            JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                            elementAdapter.write(out, obj);
                        }

                        @Override
                        public CFAuthorizationInPaymentsEntity read(JsonReader in)
                                throws IOException {
                            JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
                            validateJsonObject(jsonObj);
                            return thisAdapter.fromJsonTree(jsonObj);
                        }
                    }.nullSafe();
        }
    }

    /**
     * Create an instance of CFAuthorizationInPaymentsEntity given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of CFAuthorizationInPaymentsEntity
     * @throws IOException if the JSON string is invalid with respect to
     *     CFAuthorizationInPaymentsEntity
     */
    public static CFAuthorizationInPaymentsEntity fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, CFAuthorizationInPaymentsEntity.class);
    }

    /**
     * Convert an instance of CFAuthorizationInPaymentsEntity to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
