/*
 * New Payment Gateway APIs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2022-01-01
 * Contact: nextgenapi@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.cashfree.pg.model;


import com.cashfree.pg.JSON;
import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.HashSet;
import java.util.Map.Entry;
import java.util.Objects;
import java.util.Set;

/** CFSavedInstrumentMeta */
@javax.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        date = "2023-03-16T14:01:52.135917+05:30[Asia/Kolkata]")
public class CFSavedInstrumentMeta {
    public static final String SERIALIZED_NAME_CARD_NETWORK = "card_network";

    @SerializedName(SERIALIZED_NAME_CARD_NETWORK)
    private String cardNetwork;

    public static final String SERIALIZED_NAME_CARD_BANK_NAME = "card_bank_name";

    @SerializedName(SERIALIZED_NAME_CARD_BANK_NAME)
    private String cardBankName;

    public static final String SERIALIZED_NAME_CARD_COUNTRY = "card_country";

    @SerializedName(SERIALIZED_NAME_CARD_COUNTRY)
    private String cardCountry;

    public static final String SERIALIZED_NAME_CARD_TYPE = "card_type";

    @SerializedName(SERIALIZED_NAME_CARD_TYPE)
    private String cardType;

    public static final String SERIALIZED_NAME_CARD_SUB_TYPE = "card_sub_type";

    @SerializedName(SERIALIZED_NAME_CARD_SUB_TYPE)
    private String cardSubType;

    public static final String SERIALIZED_NAME_CARD_TOKEN_DETAILS = "card_token_details";

    @SerializedName(SERIALIZED_NAME_CARD_TOKEN_DETAILS)
    private Object cardTokenDetails;

    public CFSavedInstrumentMeta() {}

    public CFSavedInstrumentMeta cardNetwork(String cardNetwork) {

        this.cardNetwork = cardNetwork;
        return this;
    }

    /**
     * card scheme/network of the saved card
     *
     * @return cardNetwork
     */
    @javax.annotation.Nullable
    public String getCardNetwork() {
        return cardNetwork;
    }

    public void setCardNetwork(String cardNetwork) {
        this.cardNetwork = cardNetwork;
    }

    public CFSavedInstrumentMeta cardBankName(String cardBankName) {

        this.cardBankName = cardBankName;
        return this;
    }

    /**
     * Issuing bank name of saved card
     *
     * @return cardBankName
     */
    @javax.annotation.Nullable
    public String getCardBankName() {
        return cardBankName;
    }

    public void setCardBankName(String cardBankName) {
        this.cardBankName = cardBankName;
    }

    public CFSavedInstrumentMeta cardCountry(String cardCountry) {

        this.cardCountry = cardCountry;
        return this;
    }

    /**
     * Issuing country of saved card
     *
     * @return cardCountry
     */
    @javax.annotation.Nullable
    public String getCardCountry() {
        return cardCountry;
    }

    public void setCardCountry(String cardCountry) {
        this.cardCountry = cardCountry;
    }

    public CFSavedInstrumentMeta cardType(String cardType) {

        this.cardType = cardType;
        return this;
    }

    /**
     * Type of saved card
     *
     * @return cardType
     */
    @javax.annotation.Nullable
    public String getCardType() {
        return cardType;
    }

    public void setCardType(String cardType) {
        this.cardType = cardType;
    }

    public CFSavedInstrumentMeta cardSubType(String cardSubType) {

        this.cardSubType = cardSubType;
        return this;
    }

    /**
     * Sub Type of saved card
     *
     * @return cardSubType
     */
    @javax.annotation.Nullable
    public String getCardSubType() {
        return cardSubType;
    }

    public void setCardSubType(String cardSubType) {
        this.cardSubType = cardSubType;
    }

    public CFSavedInstrumentMeta cardTokenDetails(Object cardTokenDetails) {

        this.cardTokenDetails = cardTokenDetails;
        return this;
    }

    /**
     * Get cardTokenDetails
     *
     * @return cardTokenDetails
     */
    @javax.annotation.Nullable
    public Object getCardTokenDetails() {
        return cardTokenDetails;
    }

    public void setCardTokenDetails(Object cardTokenDetails) {
        this.cardTokenDetails = cardTokenDetails;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CFSavedInstrumentMeta cfSavedInstrumentMeta = (CFSavedInstrumentMeta) o;
        return Objects.equals(this.cardNetwork, cfSavedInstrumentMeta.cardNetwork)
                && Objects.equals(this.cardBankName, cfSavedInstrumentMeta.cardBankName)
                && Objects.equals(this.cardCountry, cfSavedInstrumentMeta.cardCountry)
                && Objects.equals(this.cardType, cfSavedInstrumentMeta.cardType)
                && Objects.equals(this.cardSubType, cfSavedInstrumentMeta.cardSubType)
                && Objects.equals(this.cardTokenDetails, cfSavedInstrumentMeta.cardTokenDetails);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
                cardNetwork, cardBankName, cardCountry, cardType, cardSubType, cardTokenDetails);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class CFSavedInstrumentMeta {\n");
        sb.append("    cardNetwork: ").append(toIndentedString(cardNetwork)).append("\n");
        sb.append("    cardBankName: ").append(toIndentedString(cardBankName)).append("\n");
        sb.append("    cardCountry: ").append(toIndentedString(cardCountry)).append("\n");
        sb.append("    cardType: ").append(toIndentedString(cardType)).append("\n");
        sb.append("    cardSubType: ").append(toIndentedString(cardSubType)).append("\n");
        sb.append("    cardTokenDetails: ").append(toIndentedString(cardTokenDetails)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>();
        openapiFields.add("card_network");
        openapiFields.add("card_bank_name");
        openapiFields.add("card_country");
        openapiFields.add("card_type");
        openapiFields.add("card_sub_type");
        openapiFields.add("card_token_details");

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>();
    }

    /**
     * Validates the JSON Object and throws an exception if issues found
     *
     * @param jsonObj JSON Object
     * @throws IOException if the JSON Object is invalid with respect to CFSavedInstrumentMeta
     */
    public static void validateJsonObject(JsonObject jsonObj) throws IOException {
        if (jsonObj == null) {
            if (!CFSavedInstrumentMeta.openapiRequiredFields
                    .isEmpty()) { // has required fields but JSON object is null
                throw new IllegalArgumentException(
                        String.format(
                                "The required field(s) %s in CFSavedInstrumentMeta is not found in"
                                        + " the empty JSON string",
                                CFSavedInstrumentMeta.openapiRequiredFields.toString()));
            }
        }

        Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
        // check to see if the JSON string contains additional fields
        for (Entry<String, JsonElement> entry : entries) {
            if (!CFSavedInstrumentMeta.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(
                        String.format(
                                "The field `%s` in the JSON string is not defined in the"
                                        + " `CFSavedInstrumentMeta` properties. JSON: %s",
                                entry.getKey(), jsonObj.toString()));
            }
        }
        if ((jsonObj.get("card_network") != null && !jsonObj.get("card_network").isJsonNull())
                && !jsonObj.get("card_network").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `card_network` to be a primitive type in the JSON"
                                    + " string but got `%s`",
                            jsonObj.get("card_network").toString()));
        }
        if ((jsonObj.get("card_bank_name") != null && !jsonObj.get("card_bank_name").isJsonNull())
                && !jsonObj.get("card_bank_name").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `card_bank_name` to be a primitive type in the"
                                    + " JSON string but got `%s`",
                            jsonObj.get("card_bank_name").toString()));
        }
        if ((jsonObj.get("card_country") != null && !jsonObj.get("card_country").isJsonNull())
                && !jsonObj.get("card_country").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `card_country` to be a primitive type in the JSON"
                                    + " string but got `%s`",
                            jsonObj.get("card_country").toString()));
        }
        if ((jsonObj.get("card_type") != null && !jsonObj.get("card_type").isJsonNull())
                && !jsonObj.get("card_type").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `card_type` to be a primitive type in the JSON"
                                    + " string but got `%s`",
                            jsonObj.get("card_type").toString()));
        }
        if ((jsonObj.get("card_sub_type") != null && !jsonObj.get("card_sub_type").isJsonNull())
                && !jsonObj.get("card_sub_type").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `card_sub_type` to be a primitive type in the JSON"
                                    + " string but got `%s`",
                            jsonObj.get("card_sub_type").toString()));
        }
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!CFSavedInstrumentMeta.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'CFSavedInstrumentMeta' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<CFSavedInstrumentMeta> thisAdapter =
                    gson.getDelegateAdapter(this, TypeToken.get(CFSavedInstrumentMeta.class));

            return (TypeAdapter<T>)
                    new TypeAdapter<CFSavedInstrumentMeta>() {
                        @Override
                        public void write(JsonWriter out, CFSavedInstrumentMeta value)
                                throws IOException {
                            JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                            elementAdapter.write(out, obj);
                        }

                        @Override
                        public CFSavedInstrumentMeta read(JsonReader in) throws IOException {
                            JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
                            validateJsonObject(jsonObj);
                            return thisAdapter.fromJsonTree(jsonObj);
                        }
                    }.nullSafe();
        }
    }

    /**
     * Create an instance of CFSavedInstrumentMeta given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of CFSavedInstrumentMeta
     * @throws IOException if the JSON string is invalid with respect to CFSavedInstrumentMeta
     */
    public static CFSavedInstrumentMeta fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, CFSavedInstrumentMeta.class);
    }

    /**
     * Convert an instance of CFSavedInstrumentMeta to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
