/*
 * New Payment Gateway APIs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2022-01-01
 * Contact: nextgenapi@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.cashfree.pg.model;


import com.cashfree.pg.JSON;
import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.HashSet;
import java.util.Map.Entry;
import java.util.Objects;
import java.util.Set;

/** CFUPIAuthorizeDetails */
@javax.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        date = "2023-03-16T14:01:52.135917+05:30[Asia/Kolkata]")
public class CFUPIAuthorizeDetails {
    public static final String SERIALIZED_NAME_APPROVE_BY = "approve_by";

    @SerializedName(SERIALIZED_NAME_APPROVE_BY)
    private String approveBy;

    public static final String SERIALIZED_NAME_START_TIME = "start_time";

    @SerializedName(SERIALIZED_NAME_START_TIME)
    private String startTime;

    public static final String SERIALIZED_NAME_END_TIME = "end_time";

    @SerializedName(SERIALIZED_NAME_END_TIME)
    private String endTime;

    public CFUPIAuthorizeDetails() {}

    public CFUPIAuthorizeDetails approveBy(String approveBy) {

        this.approveBy = approveBy;
        return this;
    }

    /**
     * Time by which this authorization should be approved by the customer.
     *
     * @return approveBy
     */
    @javax.annotation.Nullable
    public String getApproveBy() {
        return approveBy;
    }

    public void setApproveBy(String approveBy) {
        this.approveBy = approveBy;
    }

    public CFUPIAuthorizeDetails startTime(String startTime) {

        this.startTime = startTime;
        return this;
    }

    /**
     * This is the time when the UPI one time mandate will start
     *
     * @return startTime
     */
    @javax.annotation.Nullable
    public String getStartTime() {
        return startTime;
    }

    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    public CFUPIAuthorizeDetails endTime(String endTime) {

        this.endTime = endTime;
        return this;
    }

    /**
     * This is the time when the UPI mandate will be over. If the mandate has not been executed by
     * this time, the funds will be returned back to the customer after this time.
     *
     * @return endTime
     */
    @javax.annotation.Nullable
    public String getEndTime() {
        return endTime;
    }

    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CFUPIAuthorizeDetails cfUPIAuthorizeDetails = (CFUPIAuthorizeDetails) o;
        return Objects.equals(this.approveBy, cfUPIAuthorizeDetails.approveBy)
                && Objects.equals(this.startTime, cfUPIAuthorizeDetails.startTime)
                && Objects.equals(this.endTime, cfUPIAuthorizeDetails.endTime);
    }

    @Override
    public int hashCode() {
        return Objects.hash(approveBy, startTime, endTime);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class CFUPIAuthorizeDetails {\n");
        sb.append("    approveBy: ").append(toIndentedString(approveBy)).append("\n");
        sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
        sb.append("    endTime: ").append(toIndentedString(endTime)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>();
        openapiFields.add("approve_by");
        openapiFields.add("start_time");
        openapiFields.add("end_time");

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>();
    }

    /**
     * Validates the JSON Object and throws an exception if issues found
     *
     * @param jsonObj JSON Object
     * @throws IOException if the JSON Object is invalid with respect to CFUPIAuthorizeDetails
     */
    public static void validateJsonObject(JsonObject jsonObj) throws IOException {
        if (jsonObj == null) {
            if (!CFUPIAuthorizeDetails.openapiRequiredFields
                    .isEmpty()) { // has required fields but JSON object is null
                throw new IllegalArgumentException(
                        String.format(
                                "The required field(s) %s in CFUPIAuthorizeDetails is not found in"
                                        + " the empty JSON string",
                                CFUPIAuthorizeDetails.openapiRequiredFields.toString()));
            }
        }

        Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
        // check to see if the JSON string contains additional fields
        for (Entry<String, JsonElement> entry : entries) {
            if (!CFUPIAuthorizeDetails.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(
                        String.format(
                                "The field `%s` in the JSON string is not defined in the"
                                        + " `CFUPIAuthorizeDetails` properties. JSON: %s",
                                entry.getKey(), jsonObj.toString()));
            }
        }
        if ((jsonObj.get("approve_by") != null && !jsonObj.get("approve_by").isJsonNull())
                && !jsonObj.get("approve_by").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `approve_by` to be a primitive type in the JSON"
                                    + " string but got `%s`",
                            jsonObj.get("approve_by").toString()));
        }
        if ((jsonObj.get("start_time") != null && !jsonObj.get("start_time").isJsonNull())
                && !jsonObj.get("start_time").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `start_time` to be a primitive type in the JSON"
                                    + " string but got `%s`",
                            jsonObj.get("start_time").toString()));
        }
        if ((jsonObj.get("end_time") != null && !jsonObj.get("end_time").isJsonNull())
                && !jsonObj.get("end_time").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `end_time` to be a primitive type in the JSON"
                                    + " string but got `%s`",
                            jsonObj.get("end_time").toString()));
        }
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!CFUPIAuthorizeDetails.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'CFUPIAuthorizeDetails' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<CFUPIAuthorizeDetails> thisAdapter =
                    gson.getDelegateAdapter(this, TypeToken.get(CFUPIAuthorizeDetails.class));

            return (TypeAdapter<T>)
                    new TypeAdapter<CFUPIAuthorizeDetails>() {
                        @Override
                        public void write(JsonWriter out, CFUPIAuthorizeDetails value)
                                throws IOException {
                            JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                            elementAdapter.write(out, obj);
                        }

                        @Override
                        public CFUPIAuthorizeDetails read(JsonReader in) throws IOException {
                            JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
                            validateJsonObject(jsonObj);
                            return thisAdapter.fromJsonTree(jsonObj);
                        }
                    }.nullSafe();
        }
    }

    /**
     * Create an instance of CFUPIAuthorizeDetails given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of CFUPIAuthorizeDetails
     * @throws IOException if the JSON string is invalid with respect to CFUPIAuthorizeDetails
     */
    public static CFUPIAuthorizeDetails fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, CFUPIAuthorizeDetails.class);
    }

    /**
     * Convert an instance of CFUPIAuthorizeDetails to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
