/*
 * New Payment Gateway APIs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2022-01-01
 * Contact: nextgenapi@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.cashfree.pg.model;


import com.cashfree.pg.JSON;
import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Map.Entry;
import java.util.Objects;
import java.util.Set;

/** CFVendorSplit */
@javax.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        date = "2023-03-16T14:01:52.135917+05:30[Asia/Kolkata]")
public class CFVendorSplit {
    public static final String SERIALIZED_NAME_VENDOR_ID = "vendor_id";

    @SerializedName(SERIALIZED_NAME_VENDOR_ID)
    private String vendorId;

    public static final String SERIALIZED_NAME_AMOUNT = "amount";

    @SerializedName(SERIALIZED_NAME_AMOUNT)
    private BigDecimal amount;

    public static final String SERIALIZED_NAME_PERCENTAGE = "percentage";

    @SerializedName(SERIALIZED_NAME_PERCENTAGE)
    private BigDecimal percentage;

    public CFVendorSplit() {}

    public CFVendorSplit vendorId(String vendorId) {

        this.vendorId = vendorId;
        return this;
    }

    /**
     * Vendor id created in Cashfree system
     *
     * @return vendorId
     */
    @javax.annotation.Nullable
    public String getVendorId() {
        return vendorId;
    }

    public void setVendorId(String vendorId) {
        this.vendorId = vendorId;
    }

    public CFVendorSplit amount(BigDecimal amount) {

        this.amount = amount;
        return this;
    }

    /**
     * Amount which will be associated with this vendor
     *
     * @return amount
     */
    @javax.annotation.Nullable
    public BigDecimal getAmount() {
        return amount;
    }

    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    public CFVendorSplit percentage(BigDecimal percentage) {

        this.percentage = percentage;
        return this;
    }

    /**
     * Percentage of order amount which shall get added to vendor account
     *
     * @return percentage
     */
    @javax.annotation.Nullable
    public BigDecimal getPercentage() {
        return percentage;
    }

    public void setPercentage(BigDecimal percentage) {
        this.percentage = percentage;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CFVendorSplit cfVendorSplit = (CFVendorSplit) o;
        return Objects.equals(this.vendorId, cfVendorSplit.vendorId)
                && Objects.equals(this.amount, cfVendorSplit.amount)
                && Objects.equals(this.percentage, cfVendorSplit.percentage);
    }

    @Override
    public int hashCode() {
        return Objects.hash(vendorId, amount, percentage);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class CFVendorSplit {\n");
        sb.append("    vendorId: ").append(toIndentedString(vendorId)).append("\n");
        sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
        sb.append("    percentage: ").append(toIndentedString(percentage)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>();
        openapiFields.add("vendor_id");
        openapiFields.add("amount");
        openapiFields.add("percentage");

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>();
    }

    /**
     * Validates the JSON Object and throws an exception if issues found
     *
     * @param jsonObj JSON Object
     * @throws IOException if the JSON Object is invalid with respect to CFVendorSplit
     */
    public static void validateJsonObject(JsonObject jsonObj) throws IOException {
        if (jsonObj == null) {
            if (!CFVendorSplit.openapiRequiredFields
                    .isEmpty()) { // has required fields but JSON object is null
                throw new IllegalArgumentException(
                        String.format(
                                "The required field(s) %s in CFVendorSplit is not found in the"
                                        + " empty JSON string",
                                CFVendorSplit.openapiRequiredFields.toString()));
            }
        }

        Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
        // check to see if the JSON string contains additional fields
        for (Entry<String, JsonElement> entry : entries) {
            if (!CFVendorSplit.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(
                        String.format(
                                "The field `%s` in the JSON string is not defined in the"
                                        + " `CFVendorSplit` properties. JSON: %s",
                                entry.getKey(), jsonObj.toString()));
            }
        }
        if ((jsonObj.get("vendor_id") != null && !jsonObj.get("vendor_id").isJsonNull())
                && !jsonObj.get("vendor_id").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `vendor_id` to be a primitive type in the JSON"
                                    + " string but got `%s`",
                            jsonObj.get("vendor_id").toString()));
        }
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!CFVendorSplit.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'CFVendorSplit' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<CFVendorSplit> thisAdapter =
                    gson.getDelegateAdapter(this, TypeToken.get(CFVendorSplit.class));

            return (TypeAdapter<T>)
                    new TypeAdapter<CFVendorSplit>() {
                        @Override
                        public void write(JsonWriter out, CFVendorSplit value) throws IOException {
                            JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                            elementAdapter.write(out, obj);
                        }

                        @Override
                        public CFVendorSplit read(JsonReader in) throws IOException {
                            JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
                            validateJsonObject(jsonObj);
                            return thisAdapter.fromJsonTree(jsonObj);
                        }
                    }.nullSafe();
        }
    }

    /**
     * Create an instance of CFVendorSplit given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of CFVendorSplit
     * @throws IOException if the JSON string is invalid with respect to CFVendorSplit
     */
    public static CFVendorSplit fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, CFVendorSplit.class);
    }

    /**
     * Convert an instance of CFVendorSplit to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
